// Mocks generated by Mockito 5.3.2 from annotations
// in mikrogrup/test/features/anime_detail/presentation/pages/widget_test/anime_detail_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mikrogrup/core/errors/failures.dart' as _i6;
import 'package:mikrogrup/features/anime_detail/domain/entites/anime_detail.dart'
    as _i7;
import 'package:mikrogrup/features/anime_detail/domain/repositories/anime_detail_repository.dart'
    as _i2;
import 'package:mikrogrup/features/anime_detail/domain/uses_cases/get_anime_detail.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAnimeDetailRepository_0 extends _i1.SmartFake
    implements _i2.AnimeDetailRepository {
  _FakeAnimeDetailRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAnimeDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAnimeDetail extends _i1.Mock implements _i4.GetAnimeDetail {
  MockGetAnimeDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AnimeDetailRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAnimeDetailRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AnimeDetailRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.AnimeDetail>> call(int? animeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [animeId],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.AnimeDetail>>.value(
            _FakeEither_1<_i6.Failure, _i7.AnimeDetail>(
          this,
          Invocation.method(
            #call,
            [animeId],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.AnimeDetail>>);
}
